export const SUBMIT_FORM='SUBMIT_FORM';
export const SUBMIT_FORM_START='SUBMIT_FORM_START';
export const SUBMIT_FORM_SUCCESS='SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE='SUBMIT_FORM_FAILURE';





